# Generated by Django 3.1.1 on 2020-09-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medico',
            new_name='Medicos',
        ),
        migrations.RenameField(
            model_name='doadores',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='medicos',
            old_name='crm',
            new_name='CRM',
        ),
    ]
