# Generated by Django 3.1.1 on 2020-09-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0002_auto_20200924_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doadores',
            new_name='Doador',
        ),
        migrations.RenameModel(
            old_name='Medicos',
            new_name='Medico',
        ),
        migrations.RenameField(
            model_name='doador',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='nome_medico',
            new_name='nome',
        ),
    ]
