# Generated by Django 3.1.1 on 2020-09-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0003_auto_20200924_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doador',
            old_name='tipo_sanguineo',
            new_name='tipo_Sanguíneo',
        ),
    ]
