# Generated by Django 3.1.1 on 2020-09-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0005_auto_20200924_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doador',
            name='idade',
        ),
    ]
