# Generated by Django 3.1.1 on 2020-09-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0006_remove_doador_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='tipo_Sanguíneo',
            field=models.IntegerField(),
        ),
    ]
