# Generated by Django 3.1.1 on 2020-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0007_auto_20200924_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='tipo_Sanguíneo',
            field=models.CharField(max_length=100),
        ),
    ]
