# Generated by Django 3.1.1 on 2020-09-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0008_auto_20200924_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2),
        ),
    ]
