# Generated by Django 3.1.1 on 2020-09-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0009_auto_20200924_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='RG',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='doador',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doador',
            name='tipo_Sanguíneo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=3),
        ),
        migrations.AlterField(
            model_name='medico',
            name='CRM',
            field=models.IntegerField(max_length=14),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
