# Generated by Django 3.1.1 on 2020-09-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0010_auto_20200924_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='RG',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doador',
            name='tipo_Sanguíneo',
            field=models.CharField(choices=[(1, 'AB+'), (2, 'AB-'), (3, 'A+'), (4, 'A-'), (5, 'B+'), (6, 'B-'), (7, 'O+'), (8, 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='medico',
            name='CRM',
            field=models.IntegerField(),
        ),
    ]
