# Generated by Django 3.1.1 on 2020-09-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0011_auto_20200924_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='tipo_Sanguíneo',
            field=models.CharField(choices=[('1', 'AB+'), ('2', 'AB-'), ('3', 'A+'), ('4', 'A-'), ('5', 'B+'), ('6', 'B-'), ('7', 'O+'), ('8', 'O-')], max_length=3),
        ),
    ]
