# Generated by Django 3.1.1 on 2020-09-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0014_auto_20200924_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('1', 'Hematologista'), ('2', 'Enfermeiro'), ('3', 'Outro')], default='', editable=False, max_length=12),
        ),
    ]
