# Generated by Django 3.1.1 on 2020-09-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0016_auto_20200927_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='doador',
            name='tipo_Sanguíneo',
            field=models.CharField(choices=[('1', 'AB+'), ('2', 'AB-'), ('3', 'A+'), ('4', 'A-'), ('5', 'B+'), ('6', 'B-'), ('7', 'O+'), ('8', 'O-')], default='', max_length=3),
        ),
    ]
