# Generated by Django 3.1.1 on 2020-09-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0017_auto_20200927_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('1', 'Hematologista'), ('2', 'Enfermeira(o)'), ('3', 'Outro')], default='', max_length=12),
        ),
    ]
