# Generated by Django 3.1.1 on 2020-09-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0018_auto_20200927_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doador',
            name='sexo',
        ),
        migrations.AddField(
            model_name='doador',
            name='gênero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], default='', max_length=2),
        ),
    ]
