# Generated by Django 3.1.1 on 2020-09-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0019_auto_20200928_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='RG',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
