# Generated by Django 3.1.1 on 2020-11-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0020_auto_20200928_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='RG',
            field=models.IntegerField(),
        ),
    ]
