# Generated by Django 3.1.7 on 2021-04-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0021_auto_20201118_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doador',
            name='RG',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='gênero',
        ),
        migrations.AddField(
            model_name='doador',
            name='CPF',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='doador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='', max_length=2),
        ),
    ]
