# Generated by Django 3.1.7 on 2021-04-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacaodesangue', '0022_auto_20210401_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='CPF',
            field=models.CharField(default='', max_length=14),
        ),
    ]
